import type { FeedEvent, Garment, Outfit, Weather } from '@/types/domain'
import { daysAgo } from './mockData.dates'
import { GARMENTS_A } from './garments/partA'
import { GARMENTS_B } from './garments/partB'
import { GARMENTS_C } from './garments/partC'
import { GARMENTS_D } from './garments/partD'

/**
 * Deterministic demo dataset. Dates are expressed as day-offsets from "now" and
 * resolved once at module load, so the feed always reads as recent activity.
 * The base garments live here; ~68 more are split across part files (built in
 * parallel) and concatenated into MOCK_GARMENTS below.
 */

const BASE_GARMENTS: Garment[] = [
  {
    id: 'g-linen-shirt',
    image: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5433.png',
    name: 'Relaxed Linen Shirt',
    description: 'Breezy oversized linen shirt with a soft collar. The summer workhorse.',
    category: 'tops',
    colors: ['ivory', 'sand'],
    seasons: ['spring', 'summer'],
    brand: 'COS',
    material: 'Linen',
    timesWorn: 24,
    lastWorn: daysAgo(1, 8, 30),
    createdAt: daysAgo(210),
    favorite: true,
  },
  {
    id: 'g-charcoal-tee',
    image: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5425.png',
    name: 'Heavyweight Boxy Tee',
    description: 'Structured cotton tee that holds its shape. Everyday base layer.',
    category: 'tops',
    colors: ['charcoal', 'slate'],
    seasons: ['spring', 'summer', 'autumn'],
    brand: 'Uniqlo U',
    material: 'Cotton',
    timesWorn: 41,
    lastWorn: daysAgo(3, 9, 0),
    createdAt: daysAgo(160),
    favorite: false,
  },
  {
    id: 'g-sage-knit',
    image: 'https://pngimg.com/uploads/sweater/sweater_PNG5.png',
    name: 'Merino Crewneck',
    description: 'Fine-gauge merino in a muted sage. Layers under everything.',
    category: 'tops',
    colors: ['sage', 'olive'],
    seasons: ['autumn', 'winter'],
    brand: 'Arket',
    material: 'Merino wool',
    timesWorn: 12,
    lastWorn: daysAgo(28, 18, 0),
    createdAt: daysAgo(120),
    favorite: true,
  },
  {
    id: 'g-denim-wide',
    image: 'https://pngimg.com/uploads/jeans/jeans_PNG5745.png',
    name: 'Wide-Leg Selvedge Denim',
    description: 'Rigid selvedge denim with a high rise and a generous leg.',
    category: 'bottoms',
    colors: ['denim', 'navy'],
    seasons: ['spring', 'autumn', 'winter'],
    brand: 'Levi’s',
    material: 'Cotton denim',
    timesWorn: 33,
    lastWorn: daysAgo(2, 10, 0),
    createdAt: daysAgo(190),
    favorite: true,
  },
  {
    id: 'g-pleated-trouser',
    image: 'https://pngimg.com/uploads/jeans/jeans_PNG5750.png',
    name: 'Pleated Wool Trousers',
    description: 'Tailored pleats with a fluid drape. Dresses any top up instantly.',
    category: 'bottoms',
    colors: ['charcoal', 'slate'],
    seasons: ['autumn', 'winter'],
    brand: 'Sézane',
    material: 'Wool blend',
    timesWorn: 9,
    lastWorn: daysAgo(40, 19, 0),
    createdAt: daysAgo(95),
    favorite: false,
  },
  {
    id: 'g-linen-short',
    image: 'https://pngimg.com/uploads/leggings/leggings_PNG10.png',
    name: 'Pull-On Linen Shorts',
    description: 'Elastic-waist linen shorts. The reason summer is bearable.',
    category: 'bottoms',
    colors: ['sand', 'cream'],
    seasons: ['summer'],
    material: 'Linen',
    timesWorn: 18,
    lastWorn: daysAgo(5, 12, 0),
    createdAt: daysAgo(80),
    favorite: false,
  },
  {
    id: 'g-trench',
    image: 'https://pngimg.com/uploads/coat/coat_PNG5.png',
    name: 'Cotton Trench Coat',
    description: 'Classic belted trench in warm camel. Rain-ready and forever chic.',
    category: 'outerwear',
    colors: ['camel', 'sand'],
    seasons: ['spring', 'autumn'],
    brand: 'Burberry',
    material: 'Cotton gabardine',
    timesWorn: 15,
    lastWorn: daysAgo(9, 8, 0),
    createdAt: daysAgo(300),
    favorite: true,
  },
  {
    id: 'g-quilted-jacket',
    image: 'https://pngimg.com/uploads/jacket/jacket_PNG8025.png',
    name: 'Quilted Field Jacket',
    description: 'Diamond-quilted jacket in deep forest. Weekend armour.',
    category: 'outerwear',
    colors: ['forest', 'olive'],
    seasons: ['autumn', 'winter'],
    material: 'Nylon',
    timesWorn: 7,
    lastWorn: daysAgo(50, 11, 0),
    createdAt: daysAgo(140),
    favorite: false,
  },
  {
    id: 'g-slip-dress',
    image: 'https://pngimg.com/uploads/dress/dress_PNG100.png',
    name: 'Bias-Cut Slip Dress',
    description: 'Liquid satin slip in burgundy. From desk to dinner.',
    category: 'dresses',
    colors: ['burgundy', 'black'],
    seasons: ['summer', 'autumn'],
    brand: 'Reformation',
    material: 'Satin',
    timesWorn: 6,
    lastWorn: daysAgo(21, 20, 0),
    createdAt: daysAgo(70),
    favorite: true,
  },
  {
    id: 'g-linen-dress',
    image: 'https://pngimg.com/uploads/dress/dress_PNG105.png',
    name: 'Tiered Linen Midi',
    description: 'Airy tiered midi in ivory. The one-and-done heatwave dress.',
    category: 'dresses',
    colors: ['ivory', 'blush'],
    seasons: ['spring', 'summer'],
    material: 'Linen',
    timesWorn: 11,
    lastWorn: daysAgo(6, 13, 0),
    createdAt: daysAgo(88),
    favorite: false,
  },
  {
    id: 'g-white-sneaker',
    image: 'https://pngimg.com/uploads/running_shoes/running_shoes_PNG5780.png',
    name: 'Minimal Leather Sneakers',
    description: 'Clean off-white trainers that quietly go with everything.',
    category: 'footwear',
    colors: ['white', 'cream'],
    seasons: ['spring', 'summer', 'autumn'],
    brand: 'Common Projects',
    material: 'Leather',
    timesWorn: 52,
    lastWorn: daysAgo(1, 8, 30),
    createdAt: daysAgo(240),
    favorite: true,
  },
  {
    id: 'g-chelsea-boot',
    image: 'https://pngimg.com/uploads/boots/boots_PNG7779.png',
    name: 'Suede Chelsea Boots',
    description: 'Rust suede boots with a stacked heel. Autumn’s default.',
    category: 'footwear',
    colors: ['rust', 'camel'],
    seasons: ['autumn', 'winter'],
    material: 'Suede',
    timesWorn: 19,
    lastWorn: daysAgo(12, 9, 0),
    createdAt: daysAgo(170),
    favorite: false,
  },
  {
    id: 'g-canvas-tote',
    image: 'https://pngimg.com/uploads/backpack/backpack_PNG6310.png',
    name: 'Structured Canvas Tote',
    description: 'Roomy waxed-canvas tote in stone. Carries the whole day.',
    category: 'accessories',
    colors: ['stone', 'sand'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    material: 'Waxed canvas',
    timesWorn: 38,
    lastWorn: daysAgo(1, 8, 30),
    createdAt: daysAgo(130),
    favorite: false,
  },
  {
    id: 'g-silk-scarf',
    image: 'https://pngimg.com/uploads/scarf/scarf_PNG5.png',
    name: 'Printed Silk Scarf',
    description: 'Hand-rolled silk scarf in lilac. Instant outfit upgrade.',
    category: 'accessories',
    colors: ['lilac', 'sky'],
    seasons: ['spring', 'autumn'],
    material: 'Silk',
    timesWorn: 4,
    lastWorn: daysAgo(60, 15, 0),
    createdAt: daysAgo(65),
    favorite: false,
  },
  {
    id: 'g-wool-coat',
    image: 'https://pngimg.com/uploads/coat/coat_PNG12.png',
    name: 'Double-Faced Wool Coat',
    description: 'Longline wool coat in charcoal. The winter statement piece.',
    category: 'outerwear',
    colors: ['charcoal', 'black'],
    seasons: ['winter'],
    brand: 'Max Mara',
    material: 'Wool',
    timesWorn: 3,
    lastWorn: daysAgo(90, 8, 0),
    createdAt: daysAgo(45),
    favorite: true,
  },
  {
    id: 'g-cardigan',
    image: 'https://pngimg.com/uploads/sweater/sweater_PNG12.png',
    name: 'Chunky Ribbed Cardigan',
    description: 'Oversized ribbed cardigan in cream. Sunday morning uniform.',
    category: 'tops',
    colors: ['cream', 'sand'],
    seasons: ['autumn', 'winter'],
    material: 'Cotton',
    timesWorn: 22,
    lastWorn: daysAgo(15, 9, 0),
    createdAt: daysAgo(150),
    favorite: false,
  },
  {
    id: 'g-striped-breton',
    image: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5440.png',
    name: 'Breton Striped Top',
    description: 'Classic navy-and-cream Breton stripe. Never not right.',
    category: 'tops',
    colors: ['navy', 'cream'],
    seasons: ['spring', 'summer', 'autumn'],
    brand: 'Saint James',
    material: 'Cotton',
    timesWorn: 29,
    lastWorn: daysAgo(4, 9, 30),
    createdAt: daysAgo(200),
    favorite: true,
  },
  {
    id: 'g-mustard-turtleneck',
    image: 'https://pngimg.com/uploads/sweater/sweater_PNG20.png',
    name: 'Ribbed Mustard Turtleneck',
    description: 'Snug ribbed turtleneck in warm mustard. Brightens grey days.',
    category: 'tops',
    colors: ['mustard', 'camel'],
    seasons: ['autumn', 'winter'],
    brand: 'Mango',
    material: 'Merino wool',
    timesWorn: 14,
    lastWorn: daysAgo(33, 8, 30),
    createdAt: daysAgo(110),
    favorite: false,
  },
  {
    id: 'g-teal-blouse',
    image: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5428.png',
    name: 'Silk Wrap Blouse',
    description: 'Fluid wrap blouse in deep teal. Quietly dressy.',
    category: 'tops',
    colors: ['teal', 'emerald'],
    seasons: ['spring', 'autumn'],
    brand: 'Equipment',
    material: 'Silk',
    timesWorn: 8,
    lastWorn: daysAgo(18, 19, 0),
    createdAt: daysAgo(75),
    favorite: false,
  },
  {
    id: 'g-cargo-pants',
    image: 'https://pngimg.com/uploads/jeans/jeans_PNG5755.png',
    name: 'Relaxed Cargo Pants',
    description: 'Slouchy olive cargos with roomy pockets. Off-duty ease.',
    category: 'bottoms',
    colors: ['olive', 'khaki'],
    seasons: ['spring', 'autumn'],
    brand: 'Carhartt WIP',
    material: 'Cotton twill',
    timesWorn: 21,
    lastWorn: daysAgo(6, 11, 0),
    createdAt: daysAgo(115),
    favorite: false,
  },
  {
    id: 'g-cobalt-skirt',
    image: 'https://pngimg.com/uploads/leggings/leggings_PNG14.png',
    name: 'Pleated Midi Skirt',
    description: 'Sunray-pleated midi in vivid cobalt. Swishes beautifully.',
    category: 'bottoms',
    colors: ['cobalt', 'sky'],
    seasons: ['spring', 'summer'],
    brand: 'Sézane',
    material: 'Recycled polyester',
    timesWorn: 10,
    lastWorn: daysAgo(14, 13, 0),
    createdAt: daysAgo(90),
    favorite: true,
  },
  {
    id: 'g-cream-chino',
    image: 'https://pngimg.com/uploads/jeans/jeans_PNG5760.png',
    name: 'Straight-Leg Chinos',
    description: 'Crisp cream chinos with a clean break. Smart-casual anchor.',
    category: 'bottoms',
    colors: ['cream', 'stone'],
    seasons: ['spring', 'summer', 'autumn'],
    brand: 'Everlane',
    material: 'Cotton twill',
    timesWorn: 26,
    lastWorn: daysAgo(7, 9, 0),
    createdAt: daysAgo(135),
    favorite: false,
  },
  {
    id: 'g-teal-blazer',
    image: 'https://pngimg.com/uploads/suit/suit_PNG8118.png',
    name: 'Relaxed Teal Blazer',
    description: 'Soft-shouldered blazer in muted teal. Throws over anything.',
    category: 'outerwear',
    colors: ['teal', 'forest'],
    seasons: ['spring', 'autumn'],
    brand: 'Massimo Dutti',
    material: 'Linen blend',
    timesWorn: 13,
    lastWorn: daysAgo(11, 10, 0),
    createdAt: daysAgo(125),
    favorite: true,
  },
  {
    id: 'g-denim-jacket',
    image: 'https://pngimg.com/uploads/jacket/jacket_PNG8030.png',
    name: 'Washed Denim Jacket',
    description: 'Lived-in trucker jacket in mid denim. Layers over everything.',
    category: 'outerwear',
    colors: ['denim', 'sky'],
    seasons: ['spring', 'autumn'],
    brand: 'Levi’s',
    material: 'Cotton denim',
    timesWorn: 35,
    lastWorn: daysAgo(8, 12, 0),
    createdAt: daysAgo(220),
    favorite: false,
  },
  {
    id: 'g-puffer-vest',
    image: 'https://pngimg.com/uploads/jacket/jacket_PNG8035.png',
    name: 'Cropped Puffer Vest',
    description: 'Lightweight quilted vest in plum. Extra warmth, no bulk.',
    category: 'outerwear',
    colors: ['plum', 'burgundy'],
    seasons: ['autumn', 'winter'],
    brand: 'Uniqlo',
    material: 'Recycled nylon',
    timesWorn: 5,
    lastWorn: daysAgo(55, 9, 0),
    createdAt: daysAgo(60),
    favorite: false,
  },
  {
    id: 'g-shirt-dress',
    image: 'https://pngimg.com/uploads/dress/dress_PNG110.png',
    name: 'Poplin Shirt Dress',
    description: 'Crisp belted shirt dress in sky blue. Effortless all-day.',
    category: 'dresses',
    colors: ['sky', 'white'],
    seasons: ['spring', 'summer'],
    brand: 'Arket',
    material: 'Cotton poplin',
    timesWorn: 17,
    lastWorn: daysAgo(9, 10, 0),
    createdAt: daysAgo(98),
    favorite: true,
  },
  {
    id: 'g-emerald-wrap-dress',
    image: 'https://pngimg.com/uploads/dress/dress_PNG115.png',
    name: 'Emerald Wrap Dress',
    description: 'Jersey wrap dress in rich emerald. Flatters and travels well.',
    category: 'dresses',
    colors: ['emerald', 'forest'],
    seasons: ['autumn', 'winter'],
    brand: 'Diane von Furstenberg',
    material: 'Jersey',
    timesWorn: 9,
    lastWorn: daysAgo(24, 19, 30),
    createdAt: daysAgo(105),
    favorite: false,
  },
  {
    id: 'g-ankle-boot',
    image: 'https://pngimg.com/uploads/boots/boots_PNG7785.png',
    name: 'Black Leather Ankle Boots',
    description: 'Sleek pointed ankle boots in black. Dress or denim, done.',
    category: 'footwear',
    colors: ['black', 'charcoal'],
    seasons: ['autumn', 'winter'],
    brand: 'Vagabond',
    material: 'Leather',
    timesWorn: 31,
    lastWorn: daysAgo(5, 9, 0),
    createdAt: daysAgo(185),
    favorite: true,
  },
  {
    id: 'g-tan-loafer',
    image: 'https://pngimg.com/uploads/slippers/slippers_PNG10.png',
    name: 'Tan Leather Loafers',
    description: 'Polished penny loafers in warm chocolate tan. Smart and comfy.',
    category: 'footwear',
    colors: ['chocolate', 'camel'],
    seasons: ['spring', 'autumn'],
    brand: 'G.H. Bass',
    material: 'Leather',
    timesWorn: 16,
    lastWorn: daysAgo(13, 9, 0),
    createdAt: daysAgo(145),
    favorite: false,
  },
  {
    id: 'g-raffia-sandal',
    image: 'https://pngimg.com/uploads/sandals/sandals_PNG9671.png',
    name: 'Raffia Flat Sandals',
    description: 'Woven raffia slides in natural peach. Barefoot-easy summer.',
    category: 'footwear',
    colors: ['peach', 'sand'],
    seasons: ['summer'],
    material: 'Raffia',
    timesWorn: 20,
    lastWorn: daysAgo(4, 12, 0),
    createdAt: daysAgo(85),
    favorite: false,
  },
  {
    id: 'g-leather-belt',
    image: 'https://pngimg.com/uploads/belt/belt_PNG9564.png',
    name: 'Woven Leather Belt',
    description: 'Braided leather belt in cognac chocolate. Cinches everything.',
    category: 'accessories',
    colors: ['chocolate', 'rust'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    material: 'Leather',
    timesWorn: 27,
    lastWorn: daysAgo(5, 9, 0),
    createdAt: daysAgo(160),
    favorite: false,
  },
  {
    id: 'g-wool-beanie',
    image: 'https://pngimg.com/uploads/hat/hat_PNG5689.png',
    name: 'Ribbed Wool Beanie',
    description: 'Chunky ribbed beanie in cherry red. A pop against grey coats.',
    category: 'accessories',
    colors: ['cherry', 'burgundy'],
    seasons: ['winter'],
    brand: 'Acne Studios',
    material: 'Wool',
    timesWorn: 6,
    lastWorn: daysAgo(70, 8, 0),
    createdAt: daysAgo(50),
    favorite: true,
  },
]

/** All demo garments: the base set plus the parallel-built part files (~100 total). */
export const MOCK_GARMENTS: Garment[] = [
  ...BASE_GARMENTS,
  ...GARMENTS_A,
  ...GARMENTS_B,
  ...GARMENTS_C,
  ...GARMENTS_D,
]

export const MOCK_OUTFITS: Outfit[] = [
  {
    id: 'o-summer-linen',
    name: 'Off-Duty Linen',
    description: 'Everything breezy — the go-to for a hot commute.',
    garmentIds: ['g-linen-shirt', 'g-linen-short', 'g-white-sneaker', 'g-canvas-tote'],
    layout: 'grid',
    seasons: ['summer'],
    timesWorn: 9,
    lastWorn: daysAgo(0, 16, 30),
    createdAt: daysAgo(20),
    favorite: true,
  },
  {
    id: 'o-city-tailored',
    name: 'City Tailored',
    description: 'Pleated trousers, crisp tee, clean sneakers. Sharp but easy.',
    garmentIds: ['g-charcoal-tee', 'g-pleated-trouser', 'g-white-sneaker'],
    layout: 'cover',
    seasons: ['spring', 'autumn'],
    timesWorn: 6,
    lastWorn: daysAgo(2, 9, 0),
    createdAt: daysAgo(35),
    favorite: false,
  },
  {
    id: 'o-autumn-layers',
    name: 'Autumn Layers',
    description: 'Merino under a trench, wide denim, suede boots.',
    garmentIds: ['g-sage-knit', 'g-trench', 'g-denim-wide', 'g-chelsea-boot'],
    layout: 'canvas',
    seasons: ['autumn'],
    timesWorn: 4,
    lastWorn: daysAgo(9, 8, 0),
    createdAt: daysAgo(42),
    favorite: true,
  },
  {
    id: 'o-dinner-slip',
    name: 'Dinner Slip',
    description: 'Bias slip, wool coat, a scarf for the walk home.',
    garmentIds: ['g-slip-dress', 'g-wool-coat', 'g-silk-scarf'],
    layout: 'cover',
    seasons: ['autumn'],
    timesWorn: 2,
    lastWorn: daysAgo(21, 20, 0),
    createdAt: daysAgo(28),
    favorite: false,
  },
  {
    id: 'o-weekend-field',
    name: 'Weekend Field',
    description: 'Quilted jacket, cardigan, denim. Made for market runs.',
    garmentIds: ['g-quilted-jacket', 'g-cardigan', 'g-denim-wide', 'g-chelsea-boot'],
    layout: 'grid',
    seasons: ['autumn', 'winter'],
    timesWorn: 3,
    lastWorn: daysAgo(15, 10, 0),
    createdAt: daysAgo(30),
    favorite: false,
  },
  {
    id: 'o-heatwave',
    name: 'Heatwave Midi',
    description: 'One tiered dress, sneakers, tote. Done in ten seconds.',
    garmentIds: ['g-linen-dress', 'g-white-sneaker', 'g-canvas-tote'],
    layout: 'canvas',
    seasons: ['summer'],
    timesWorn: 5,
    lastWorn: daysAgo(6, 13, 0),
    createdAt: daysAgo(18),
    favorite: true,
  },
  {
    id: 'o-breton-cobalt',
    name: 'Stripes & Cobalt',
    description: 'Breton top, pleated cobalt skirt, raffia slides. Riviera-ready.',
    garmentIds: ['g-striped-breton', 'g-cobalt-skirt', 'g-raffia-sandal', 'g-canvas-tote'],
    layout: 'grid',
    seasons: ['summer'],
    timesWorn: 4,
    lastWorn: daysAgo(4, 12, 0),
    createdAt: daysAgo(22),
    favorite: true,
  },
  {
    id: 'o-teal-tailored',
    name: 'Teal Tailoring',
    description: 'Teal blazer over cream chinos with tan loafers. Polished ease.',
    garmentIds: ['g-teal-blazer', 'g-charcoal-tee', 'g-cream-chino', 'g-tan-loafer', 'g-leather-belt'],
    layout: 'canvas',
    seasons: ['spring', 'autumn'],
    timesWorn: 3,
    lastWorn: daysAgo(11, 10, 0),
    createdAt: daysAgo(26),
    favorite: false,
  },
  {
    id: 'o-emerald-evening',
    name: 'Emerald Evening',
    description: 'Emerald wrap dress, ankle boots, wool coat. Cold-night polish.',
    garmentIds: ['g-emerald-wrap-dress', 'g-ankle-boot', 'g-wool-coat', 'g-wool-beanie'],
    layout: 'cover',
    seasons: ['autumn', 'winter'],
    timesWorn: 2,
    lastWorn: daysAgo(24, 19, 30),
    createdAt: daysAgo(15),
    favorite: true,
  },
  {
    id: 'o-denim-mustard',
    name: 'Denim & Mustard',
    description: 'Mustard turtleneck under a denim jacket with cargos. Weekend warm.',
    garmentIds: ['g-mustard-turtleneck', 'g-denim-jacket', 'g-cargo-pants', 'g-chelsea-boot'],
    layout: 'grid',
    seasons: ['autumn'],
    timesWorn: 6,
    lastWorn: daysAgo(8, 12, 0),
    createdAt: daysAgo(38),
    favorite: false,
  },
  {
    id: 'o-cotton-crew-denim',
    name: 'Clean Cotton Casual',
    description: 'A soft v-neck, slim dark denim and white leather sneakers. The daily default.',
    garmentIds: ['g-a01', 'g-b01', 'g-c10', 'g-d01'],
    layout: 'grid',
    seasons: ['spring', 'summer'],
    timesWorn: 12,
    lastWorn: daysAgo(1, 9, 20),
    createdAt: daysAgo(24),
    favorite: true,
  },
  {
    id: 'o-aran-parka',
    name: 'Snow-Day Aran',
    description: 'Chunky cable knit under a hooded parka, beanie and boots. Built for the cold.',
    garmentIds: ['g-a11', 'g-b02', 'g-c04', 'g-d05', 'g-c13'],
    layout: 'canvas',
    seasons: ['winter'],
    timesWorn: 5,
    lastWorn: daysAgo(12, 8, 30),
    createdAt: daysAgo(46),
    favorite: false,
  },
  {
    id: 'o-polo-linen-blazer',
    name: 'Smart Linen',
    description: 'Piqué polo, wide ponte trousers and a linen blazer over suede loafers.',
    garmentIds: ['g-a09', 'g-b10', 'g-c09', 'g-c17'],
    layout: 'cover',
    seasons: ['spring', 'summer'],
    timesWorn: 4,
    lastWorn: daysAgo(5, 11, 0),
    createdAt: daysAgo(29),
    favorite: false,
  },
  {
    id: 'o-lbd-biker',
    name: 'LBD After Dark',
    description: 'Little black dress, leather biker and ankle boots. Zero hesitation.',
    garmentIds: ['g-b16', 'g-c07', 'g-c14', 'g-d15'],
    layout: 'cover',
    seasons: ['autumn', 'spring'],
    timesWorn: 7,
    lastWorn: daysAgo(3, 20, 45),
    createdAt: daysAgo(33),
    favorite: true,
  },
  {
    id: 'o-sundress-straw',
    name: 'Sun & Sandals',
    description: 'Tiered sundress, a wide-brim hat and strappy sandals with a crossbody.',
    garmentIds: ['g-b15', 'g-d07', 'g-c15', 'g-d03'],
    layout: 'grid',
    seasons: ['summer'],
    timesWorn: 6,
    lastWorn: daysAgo(2, 13, 15),
    createdAt: daysAgo(19),
    favorite: true,
  },
  {
    id: 'o-hoodie-run',
    name: 'Easy Athleisure',
    description: 'Zip hoodie, high-waist leggings, trainers and a cap. Coffee-run comfort.',
    garmentIds: ['g-a15', 'g-b07', 'g-c11', 'g-d06'],
    layout: 'grid',
    seasons: ['spring', 'autumn'],
    timesWorn: 15,
    lastWorn: daysAgo(0, 7, 40),
    createdAt: daysAgo(27),
    favorite: false,
  },
  {
    id: 'o-turtleneck-trench',
    name: 'Trench Weather',
    description: 'Cashmere turtleneck, mom jeans and a trench with a chunky scarf and boots.',
    garmentIds: ['g-a14', 'g-b03', 'g-c01', 'g-d09', 'g-c12'],
    layout: 'canvas',
    seasons: ['autumn'],
    timesWorn: 8,
    lastWorn: daysAgo(6, 9, 10),
    createdAt: daysAgo(40),
    favorite: true,
  },
  {
    id: 'o-wrap-camel',
    name: 'Camel Wrap Office',
    description: 'A crepe wrap dress under a camel coat, finished with loafers and a silk scarf.',
    garmentIds: ['g-b14', 'g-c03', 'g-c17', 'g-d10'],
    layout: 'cover',
    seasons: ['autumn', 'winter'],
    timesWorn: 3,
    lastWorn: daysAgo(10, 8, 50),
    createdAt: daysAgo(21),
    favorite: false,
  },
]

export const MOCK_FEED: FeedEvent[] = [
  { id: 'f1', type: 'outfit_worn', refId: 'o-summer-linen', at: daysAgo(0, 16, 30) },
  { id: 'f2', type: 'outfit_created', refId: 'o-summer-linen', at: daysAgo(0, 16, 15) },
  { id: 'f3', type: 'outfit_created', refId: 'o-heatwave', at: daysAgo(0, 12, 30) },
  { id: 'f4', type: 'garment_created', refId: 'g-linen-shirt', at: daysAgo(1, 16, 6) },
  { id: 'f5', type: 'outfit_worn', refId: 'o-city-tailored', at: daysAgo(1, 10, 5) },
  { id: 'f6', type: 'garment_created', refId: 'g-white-sneaker', at: daysAgo(1, 9, 3) },
  { id: 'f7', type: 'garment_created', refId: 'g-canvas-tote', at: daysAgo(1, 9, 1) },
  { id: 'f8', type: 'garment_worn', refId: 'g-charcoal-tee', at: daysAgo(3, 9, 0) },
  { id: 'f9', type: 'outfit_worn', refId: 'o-hoodie-run', at: daysAgo(0, 7, 40) },
  { id: 'f10', type: 'outfit_worn', refId: 'o-cotton-crew-denim', at: daysAgo(1, 9, 20) },
  { id: 'f11', type: 'outfit_created', refId: 'o-lbd-biker', at: daysAgo(2, 18, 5) },
  { id: 'f12', type: 'garment_created', refId: 'g-a11', at: daysAgo(2, 11, 12) },
  { id: 'f13', type: 'outfit_worn', refId: 'o-sundress-straw', at: daysAgo(2, 13, 15) },
  { id: 'f14', type: 'garment_created', refId: 'g-c07', at: daysAgo(4, 15, 30) },
  { id: 'f15', type: 'outfit_created', refId: 'o-turtleneck-trench', at: daysAgo(4, 10, 0) },
  { id: 'f16', type: 'garment_worn', refId: 'g-b16', at: daysAgo(3, 20, 45) },
]

export const MOCK_WEATHER: Weather = {
  tempC: 8,
  condition: 'rain',
  precipitationMm: 0,
  windKmh: 5,
  humidity: 96,
  uvIndex: 2,
  sunset: '18:30',
  city: 'Kyiv',
}
