import type { Garment } from '@/types/domain'
import { daysAgo } from '../mockData.dates'

/** Demo garments — part C: 9 outerwear + 8 footwear. Transparent product PNGs (pngimg.com). */
export const GARMENTS_C: Garment[] = [
  // ── Outerwear ──────────────────────────────────────────────
  {
    id: 'g-c01',
    name: 'Classic Trench Coat',
    description: 'Double-breasted cotton-gabardine trench with a storm flap and belted waist.',
    category: 'outerwear',
    image: 'https://pngimg.com/uploads/coat/coat_PNG1.png',
    colors: ['camel', 'sand'],
    seasons: ['spring', 'autumn'],
    brand: 'Aquascutum',
    material: 'Cotton gabardine',
    timesWorn: 24,
    lastWorn: daysAgo(9, 8, 30),
    createdAt: daysAgo(280),
    favorite: true,
  },
  {
    id: 'g-c02',
    name: 'Wool Overcoat',
    description: 'Single-breasted knee-length overcoat in a brushed wool blend.',
    category: 'outerwear',
    image: 'https://pngimg.com/uploads/coat/coat_PNG10.png',
    colors: ['charcoal'],
    seasons: ['autumn', 'winter'],
    brand: 'COS',
    material: 'Wool blend',
    timesWorn: 31,
    lastWorn: daysAgo(21, 9, 5),
    createdAt: daysAgo(300),
    favorite: false,
  },
  {
    id: 'g-c03',
    name: 'Camel Wrap Coat',
    description: 'Collarless wrap coat in virgin wool, tied at the waist for a clean drape.',
    category: 'outerwear',
    image: 'https://pngimg.com/uploads/coat/coat_PNG20.png',
    colors: ['camel'],
    seasons: ['autumn', 'winter'],
    brand: 'Max Mara',
    material: 'Virgin wool',
    timesWorn: 12,
    lastWorn: daysAgo(46, 10, 15),
    createdAt: daysAgo(210),
    favorite: true,
  },
  {
    id: 'g-c04',
    name: 'Hooded Parka',
    description: 'Insulated nylon parka with a fur-trim hood and drawcord hem.',
    category: 'outerwear',
    image: 'https://pngimg.com/uploads/coat/coat_PNG30.png',
    colors: ['olive'],
    seasons: ['winter'],
    brand: 'The North Face',
    material: 'Nylon shell',
    timesWorn: 18,
    lastWorn: daysAgo(64, 7, 45),
    createdAt: daysAgo(190),
    favorite: false,
  },
  {
    id: 'g-c05',
    name: 'Denim Jacket',
    description: 'Trucker-cut denim jacket with a slightly cropped, boxy fit.',
    category: 'outerwear',
    image: 'https://pngimg.com/uploads/jacket/jacket_PNG8025.png',
    colors: ['denim', 'navy'],
    seasons: ['spring', 'autumn'],
    brand: "Levi's",
    material: 'Cotton denim',
    timesWorn: 42,
    lastWorn: daysAgo(4, 14, 20),
    createdAt: daysAgo(160),
    favorite: true,
  },
  {
    id: 'g-c06',
    name: 'Bomber Jacket',
    description: 'MA-1 style bomber with ribbed cuffs and a utility sleeve pocket.',
    category: 'outerwear',
    image: 'https://pngimg.com/uploads/jacket/jacket_PNG8030.png',
    colors: ['forest'],
    seasons: ['spring', 'autumn'],
    brand: 'Alpha Industries',
    material: 'Nylon',
    timesWorn: 27,
    lastWorn: daysAgo(13, 18, 0),
    createdAt: daysAgo(140),
    favorite: false,
  },
  {
    id: 'g-c07',
    name: 'Leather Biker Jacket',
    description: 'Asymmetric-zip biker jacket in supple lambskin with quilted shoulders.',
    category: 'outerwear',
    image: 'https://pngimg.com/uploads/jacket/jacket_PNG8040.png',
    colors: ['black'],
    seasons: ['autumn', 'spring'],
    brand: 'AllSaints',
    material: 'Lambskin leather',
    timesWorn: 15,
    lastWorn: daysAgo(33, 20, 10),
    createdAt: daysAgo(120),
    favorite: true,
  },
  {
    id: 'g-c08',
    name: 'Tailored Blazer',
    description: 'Two-button tailored blazer in a fine wool with structured shoulders.',
    category: 'outerwear',
    image: 'https://pngimg.com/uploads/suit/suit_PNG8118.png',
    colors: ['navy'],
    seasons: ['spring', 'summer', 'autumn'],
    brand: 'Theory',
    material: 'Wool',
    timesWorn: 9,
    lastWorn: daysAgo(51, 9, 30),
    createdAt: daysAgo(95),
    favorite: false,
  },
  {
    id: 'g-c09',
    name: 'Linen Blazer',
    description: 'Unstructured summer blazer in breathable linen with patch pockets.',
    category: 'outerwear',
    image: 'https://pngimg.com/uploads/suit/suit_PNG8120.png',
    colors: ['stone', 'sand'],
    seasons: ['spring', 'summer'],
    brand: 'Suitsupply',
    material: 'Linen',
    timesWorn: 6,
    lastWorn: null,
    createdAt: daysAgo(70),
    favorite: false,
  },

  // ── Footwear ───────────────────────────────────────────────
  {
    id: 'g-c10',
    name: 'White Leather Sneakers',
    description: 'Minimal low-top sneakers in full-grain leather with a cupsole.',
    category: 'footwear',
    image: 'https://pngimg.com/uploads/running_shoes/running_shoes_PNG5780.png',
    colors: ['white'],
    seasons: ['spring', 'summer', 'autumn'],
    brand: 'Common Projects',
    material: 'Leather',
    timesWorn: 55,
    lastWorn: daysAgo(2, 11, 40),
    createdAt: daysAgo(200),
    favorite: true,
  },
  {
    id: 'g-c11',
    name: 'Running Trainers',
    description: 'Cushioned road-running trainers with an engineered mesh upper.',
    category: 'footwear',
    image: 'https://pngimg.com/uploads/running_shoes/running_shoes_PNG5790.png',
    colors: ['black', 'white'],
    seasons: ['spring', 'summer', 'autumn'],
    brand: 'Nike',
    material: 'Mesh',
    timesWorn: 60,
    lastWorn: daysAgo(1, 7, 15),
    createdAt: daysAgo(175),
    favorite: false,
  },
  {
    id: 'g-c12',
    name: 'Lace-Up Leather Boots',
    description: 'Eight-eye lace-up boots on an air-cushioned sole, built to last.',
    category: 'footwear',
    image: 'https://pngimg.com/uploads/boots/boots_PNG7779.png',
    colors: ['chocolate'],
    seasons: ['autumn', 'winter'],
    brand: 'Dr. Martens',
    material: 'Smooth leather',
    timesWorn: 22,
    lastWorn: daysAgo(28, 16, 50),
    createdAt: daysAgo(150),
    favorite: true,
  },
  {
    id: 'g-c13',
    name: 'Chelsea Boots',
    description: 'Elastic-gusset Chelsea boots in oiled suede with a chunky sole.',
    category: 'footwear',
    image: 'https://pngimg.com/uploads/boots/boots_PNG7790.png',
    colors: ['stone'],
    seasons: ['autumn', 'winter', 'spring'],
    brand: 'Blundstone',
    material: 'Oiled suede',
    timesWorn: 34,
    lastWorn: daysAgo(11, 8, 25),
    createdAt: daysAgo(130),
    favorite: false,
  },
  {
    id: 'g-c14',
    name: 'Ankle Boots',
    description: 'Sleek pointed ankle boots with a stacked block heel.',
    category: 'footwear',
    image: 'https://pngimg.com/uploads/boots/boots_PNG7800.png',
    colors: ['black'],
    seasons: ['autumn', 'winter'],
    brand: 'Vagabond',
    material: 'Leather',
    timesWorn: 17,
    lastWorn: daysAgo(40, 19, 5),
    createdAt: daysAgo(110),
    favorite: true,
  },
  {
    id: 'g-c15',
    name: 'Strappy Sandals',
    description: 'Two-strap footbed sandals with a contoured cork insole.',
    category: 'footwear',
    image: 'https://pngimg.com/uploads/sandals/sandals_PNG9671.png',
    colors: ['sand'],
    seasons: ['summer'],
    brand: 'Birkenstock',
    material: 'Leather',
    timesWorn: 29,
    lastWorn: daysAgo(19, 12, 0),
    createdAt: daysAgo(85),
    favorite: false,
  },
  {
    id: 'g-c16',
    name: 'Sport Slide Sandals',
    description: 'Quick-dry slide sandals with a hook-and-loop strap for adjustable fit.',
    category: 'footwear',
    image: 'https://pngimg.com/uploads/sandals/sandals_PNG9680.png',
    colors: ['navy'],
    seasons: ['summer'],
    brand: 'Teva',
    material: 'Synthetic',
    timesWorn: 8,
    lastWorn: daysAgo(57, 15, 30),
    createdAt: daysAgo(45),
    favorite: false,
  },
  {
    id: 'g-c17',
    name: 'Suede Loafers',
    description: 'Slip-on penny loafers in soft suede with a low leather heel.',
    category: 'footwear',
    image: 'https://pngimg.com/uploads/slippers/slippers_PNG1.png',
    colors: ['burgundy'],
    seasons: ['spring', 'autumn'],
    brand: 'G.H. Bass',
    material: 'Suede',
    timesWorn: 0,
    lastWorn: null,
    createdAt: daysAgo(18),
    favorite: false,
  },
]
