import type { Garment } from '@/types/domain'
import { daysAgo } from '../mockData.dates'

/** Demo dataset — part D: 17 accessories (bags, hats, scarves, belts, eyewear, gloves). */
export const GARMENTS_D: Garment[] = [
  {
    id: 'g-d01',
    name: 'Everyday Canvas Tote',
    description: 'Roomy structured tote with leather handles for the daily commute.',
    category: 'accessories',
    image: 'https://pngimg.com/uploads/backpack/backpack_PNG6310.png',
    colors: ['sand', 'camel'],
    seasons: ['spring', 'summer', 'autumn'],
    brand: 'Baggu',
    material: 'Cotton canvas',
    timesWorn: 34,
    lastWorn: daysAgo(3, 9, 20),
    createdAt: daysAgo(180),
    favorite: true,
  },
  {
    id: 'g-d02',
    name: 'Metro Leather Backpack',
    description: 'Minimal city backpack with a padded laptop sleeve.',
    category: 'accessories',
    image: 'https://pngimg.com/uploads/backpack/backpack_PNG6320.png',
    colors: ['chocolate'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    brand: 'Fjällräven',
    material: 'Full-grain leather',
    timesWorn: 22,
    lastWorn: daysAgo(9, 8, 15),
    createdAt: daysAgo(140),
    favorite: false,
  },
  {
    id: 'g-d03',
    name: 'Saddle Crossbody Bag',
    description: 'Compact crossbody with an adjustable strap and flap closure.',
    category: 'accessories',
    image: 'https://pngimg.com/uploads/backpack/backpack_PNG6330.png',
    colors: ['camel', 'cream'],
    seasons: ['spring', 'summer', 'autumn'],
    brand: 'Mango',
    material: 'Vegan leather',
    timesWorn: 18,
    lastWorn: daysAgo(6, 18, 40),
    createdAt: daysAgo(95),
    favorite: true,
  },
  {
    id: 'g-d04',
    name: 'Weekender Duffel',
    description: 'Waxed canvas holdall sized for a two-night trip.',
    category: 'accessories',
    image: 'https://pngimg.com/uploads/backpack/backpack_PNG6340.png',
    colors: ['olive'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    brand: 'Herschel',
    material: 'Waxed canvas',
    timesWorn: 7,
    lastWorn: daysAgo(21, 7, 30),
    createdAt: daysAgo(260),
    favorite: false,
  },
  {
    id: 'g-d05',
    name: 'Ribbed Wool Beanie',
    description: 'Fold-over ribbed beanie that hugs the ears on cold mornings.',
    category: 'accessories',
    image: 'https://pngimg.com/uploads/hat/hat_PNG5689.png',
    colors: ['charcoal'],
    seasons: ['autumn', 'winter'],
    brand: 'Carhartt',
    material: 'Merino wool',
    timesWorn: 41,
    lastWorn: daysAgo(120, 8, 10),
    createdAt: daysAgo(300),
    favorite: true,
  },
  {
    id: 'g-d06',
    name: 'Cotton Baseball Cap',
    description: 'Six-panel cap with a curved brim and brass adjuster.',
    category: 'accessories',
    image: 'https://pngimg.com/uploads/hat/hat_PNG5700.png',
    colors: ['navy'],
    seasons: ['spring', 'summer'],
    brand: 'Uniqlo',
    material: 'Cotton twill',
    timesWorn: 29,
    lastWorn: daysAgo(2, 14, 5),
    createdAt: daysAgo(210),
    favorite: false,
  },
  {
    id: 'g-d07',
    name: 'Wide-Brim Sun Hat',
    description: 'Packable straw hat with a generous brim for bright days.',
    category: 'accessories',
    image: 'https://pngimg.com/uploads/hat/hat_PNG5710.png',
    colors: ['ivory', 'sand'],
    seasons: ['summer'],
    brand: 'Lack of Color',
    material: 'Woven straw',
    timesWorn: 15,
    lastWorn: daysAgo(5, 11, 0),
    createdAt: daysAgo(75),
    favorite: true,
  },
  {
    id: 'g-d08',
    name: 'Corduroy Bucket Hat',
    description: 'Soft corduroy bucket hat for crisp autumn walks.',
    category: 'accessories',
    image: 'https://pngimg.com/uploads/hat/hat_PNG5695.png',
    colors: ['rust'],
    seasons: ['autumn'],
    brand: '& Other Stories',
    material: 'Cotton corduroy',
    timesWorn: 9,
    lastWorn: daysAgo(40, 16, 20),
    createdAt: daysAgo(150),
    favorite: false,
  },
  {
    id: 'g-d09',
    name: 'Chunky Knit Scarf',
    description: 'Oversized cable-knit scarf that doubles as a wrap.',
    category: 'accessories',
    image: 'https://pngimg.com/uploads/scarf/scarf_PNG1.png',
    colors: ['burgundy'],
    seasons: ['winter'],
    brand: 'COS',
    material: 'Lambswool',
    timesWorn: 26,
    lastWorn: daysAgo(150, 9, 45),
    createdAt: daysAgo(310),
    favorite: false,
  },
  {
    id: 'g-d10',
    name: 'Silk Neck Scarf',
    description: 'Lightweight printed square to knot at the neck or bag handle.',
    category: 'accessories',
    image: 'https://pngimg.com/uploads/scarf/scarf_PNG20.png',
    colors: ['blush', 'cream'],
    seasons: ['spring', 'summer'],
    brand: 'Zara',
    material: 'Silk',
    timesWorn: 12,
    lastWorn: daysAgo(8, 10, 30),
    createdAt: daysAgo(60),
    favorite: true,
  },
  {
    id: 'g-d11',
    name: 'Plaid Blanket Scarf',
    description: 'Extra-large brushed check scarf for layering over coats.',
    category: 'accessories',
    image: 'https://pngimg.com/uploads/scarf/scarf_PNG40.png',
    colors: ['forest', 'charcoal'],
    seasons: ['autumn', 'winter'],
    brand: 'Acne Studios',
    material: 'Wool blend',
    timesWorn: 20,
    lastWorn: daysAgo(130, 7, 50),
    createdAt: daysAgo(280),
    favorite: false,
  },
  {
    id: 'g-d12',
    name: 'Classic Leather Belt',
    description: 'Everyday belt with a brushed silver buckle.',
    category: 'accessories',
    image: 'https://pngimg.com/uploads/belt/belt_PNG9564.png',
    colors: ['chocolate'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    brand: "Levi's",
    material: 'Full-grain leather',
    timesWorn: 48,
    lastWorn: daysAgo(1, 8, 0),
    createdAt: daysAgo(220),
    favorite: true,
  },
  {
    id: 'g-d13',
    name: 'Woven Braided Belt',
    description: 'Stretch-woven belt with a leather-tipped tail.',
    category: 'accessories',
    image: 'https://pngimg.com/uploads/belt/belt_PNG9580.png',
    colors: ['camel'],
    seasons: ['spring', 'summer', 'autumn'],
    brand: "Anderson's",
    material: 'Woven leather',
    timesWorn: 11,
    lastWorn: daysAgo(14, 12, 15),
    createdAt: daysAgo(110),
    favorite: false,
  },
  {
    id: 'g-d14',
    name: 'Aviator Sunglasses',
    description: 'Teardrop metal frames with polarised lenses.',
    category: 'accessories',
    image: 'https://pngimg.com/uploads/sunglasses/sunglasses_PNG1.png',
    colors: ['graphite'],
    seasons: ['spring', 'summer'],
    brand: 'Ray-Ban',
    material: 'Metal',
    timesWorn: 38,
    lastWorn: daysAgo(4, 13, 25),
    createdAt: daysAgo(190),
    favorite: true,
  },
  {
    id: 'g-d15',
    name: 'Round Acetate Sunglasses',
    description: 'Slim round frames with gradient tinted lenses.',
    category: 'accessories',
    image: 'https://pngimg.com/uploads/sunglasses/sunglasses_PNG100.png',
    colors: ['black'],
    seasons: ['spring', 'summer', 'autumn'],
    brand: 'Le Specs',
    material: 'Acetate',
    timesWorn: 16,
    lastWorn: daysAgo(10, 15, 40),
    createdAt: daysAgo(85),
    favorite: false,
  },
  {
    id: 'g-d16',
    name: 'Tortoise Reading Glasses',
    description: 'Keyhole-bridge frames for screen time and long reads.',
    category: 'accessories',
    image: 'https://pngimg.com/uploads/glasses/glasses_PNG1.png',
    colors: ['chocolate', 'sand'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    brand: 'Warby Parker',
    material: 'Acetate',
    timesWorn: 52,
    lastWorn: daysAgo(0, 21, 10),
    createdAt: daysAgo(240),
    favorite: false,
  },
  {
    id: 'g-d17',
    name: 'Lambskin Leather Gloves',
    description: 'Cashmere-lined gloves, still boxed for the first cold snap.',
    category: 'accessories',
    image: 'https://pngimg.com/uploads/gloves/gloves_PNG80221.png',
    colors: ['black'],
    seasons: ['autumn', 'winter'],
    brand: 'Dents',
    material: 'Lambskin',
    timesWorn: 0,
    lastWorn: null,
    createdAt: daysAgo(30),
    favorite: false,
  },
]
