import type { Garment } from '@/types/domain'
import { daysAgo } from '../mockData.dates'

/** Demo TOP garments — part A (17). Split out so the dataset can be built in parallel. */
export const GARMENTS_A: Garment[] = [
  {
    id: 'g-a01',
    name: 'Pima Cotton V-Neck Tee',
    description: 'Silky Pima V-neck with a clean drape. The everyday layering tee.',
    category: 'tops',
    image: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5426.png',
    colors: ['white', 'stone'],
    seasons: ['spring', 'summer'],
    brand: 'Everlane',
    material: 'Pima cotton',
    timesWorn: 34,
    lastWorn: daysAgo(2, 9, 15),
    createdAt: daysAgo(140),
    favorite: true,
  },
  {
    id: 'g-a02',
    name: 'Supima Pocket Crew Tee',
    description: 'Soft crewneck with a single chest pocket. Wears in beautifully.',
    category: 'tops',
    image: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5427.png',
    colors: ['sage'],
    seasons: ['spring', 'summer', 'autumn'],
    brand: 'Uniqlo',
    material: 'Cotton',
    timesWorn: 47,
    lastWorn: daysAgo(1, 8, 45),
    createdAt: daysAgo(120),
    favorite: false,
  },
  {
    id: 'g-a03',
    name: 'Slub Cotton Long Sleeve',
    description: 'Textured slub-cotton long sleeve in warm terracotta. Easy autumn base.',
    category: 'tops',
    image: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5429.png',
    colors: ['terracotta', 'rust'],
    seasons: ['spring', 'autumn'],
    brand: 'Madewell',
    material: 'Slub cotton',
    timesWorn: 19,
    lastWorn: daysAgo(11, 10, 0),
    createdAt: daysAgo(95),
    favorite: false,
  },
  {
    id: 'g-a04',
    name: 'Contrast Ringer Tee',
    description: 'Retro ringer tee with tipped collar and cuffs. Summer nostalgia.',
    category: 'tops',
    image: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5430.png',
    colors: ['navy', 'white'],
    seasons: ['summer'],
    brand: 'Sunspel',
    material: 'Cotton',
    timesWorn: 22,
    lastWorn: daysAgo(6, 12, 30),
    createdAt: daysAgo(70),
    favorite: true,
  },
  {
    id: 'g-a05',
    name: 'Boxy Washed Tee',
    description: 'Heavyweight boxy tee with a lived-in wash. Holds its shape all day.',
    category: 'tops',
    image: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5431.png',
    colors: ['black'],
    seasons: ['spring', 'summer'],
    brand: 'Carhartt WIP',
    material: 'Cotton',
    timesWorn: 15,
    lastWorn: daysAgo(9, 11, 0),
    createdAt: daysAgo(60),
    favorite: false,
  },
  {
    id: 'g-a06',
    name: 'Waffle Henley',
    description: 'Three-button waffle henley in charcoal. The cabin-weekend staple.',
    category: 'tops',
    image: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5432.png',
    colors: ['charcoal', 'graphite'],
    seasons: ['autumn', 'winter'],
    brand: 'J.Crew',
    material: 'Waffle cotton',
    timesWorn: 28,
    lastWorn: daysAgo(4, 8, 30),
    createdAt: daysAgo(180),
    favorite: true,
  },
  {
    id: 'g-a07',
    name: 'Linen-Blend Crew Tee',
    description: 'Airy linen-blend tee in soft sand. Breathes through the heatwave.',
    category: 'tops',
    image: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5434.png',
    colors: ['sand', 'cream'],
    seasons: ['summer'],
    brand: 'COS',
    material: 'Linen blend',
    timesWorn: 11,
    lastWorn: daysAgo(14, 13, 0),
    createdAt: daysAgo(50),
    favorite: false,
  },
  {
    id: 'g-a08',
    name: 'Thermal Mockneck Base Layer',
    description: 'Slim brushed mockneck that traps heat without bulk. Ski-trip essential.',
    category: 'tops',
    image: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5435.png',
    colors: ['slate'],
    seasons: ['winter'],
    brand: 'Uniqlo Heattech',
    material: 'Polyester blend',
    timesWorn: 8,
    lastWorn: daysAgo(35, 7, 45),
    createdAt: daysAgo(40),
    favorite: false,
  },
  {
    id: 'g-a09',
    name: 'Piqué Polo Shirt',
    description: 'Classic piqué polo in muted olive. Smartens up shorts instantly.',
    category: 'tops',
    image: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5436.png',
    colors: ['olive', 'khaki'],
    seasons: ['spring', 'summer'],
    brand: 'Fred Perry',
    material: 'Piqué cotton',
    timesWorn: 17,
    lastWorn: daysAgo(8, 10, 0),
    createdAt: daysAgo(110),
    favorite: false,
  },
  {
    id: 'g-a10',
    name: 'Lambswool Crew Sweater',
    description: 'Fine lambswool crew in deep burgundy. Cosy without the weight.',
    category: 'tops',
    image: 'https://pngimg.com/uploads/sweater/sweater_PNG30.png',
    colors: ['burgundy'],
    seasons: ['autumn', 'winter'],
    brand: "Jamieson's",
    material: 'Lambswool',
    timesWorn: 13,
    lastWorn: daysAgo(20, 18, 0),
    createdAt: daysAgo(160),
    favorite: true,
  },
  {
    id: 'g-a11',
    name: 'Aran Cable-Knit Sweater',
    description: 'Hand-framed cable knit in undyed ivory. A proper winter heirloom.',
    category: 'tops',
    image: 'https://pngimg.com/uploads/sweater/sweater_PNG31.png',
    colors: ['ivory', 'cream'],
    seasons: ['winter'],
    brand: 'Aran Woollen Mills',
    material: 'Wool',
    timesWorn: 6,
    lastWorn: daysAgo(45, 9, 0),
    createdAt: daysAgo(200),
    favorite: false,
  },
  {
    id: 'g-a12',
    name: 'Mohair Boat-Neck Jumper',
    description: 'Brushed mohair boat-neck in soft blush. Fuzzy, light, a little fancy.',
    category: 'tops',
    image: 'https://pngimg.com/uploads/sweater/sweater_PNG32.png',
    colors: ['blush', 'lilac'],
    seasons: ['autumn'],
    brand: '& Other Stories',
    material: 'Mohair blend',
    timesWorn: 9,
    lastWorn: daysAgo(26, 19, 0),
    createdAt: daysAgo(88),
    favorite: false,
  },
  {
    id: 'g-a13',
    name: 'Half-Zip Fleece Pullover',
    description: 'Cosy recycled-fleece half-zip in forest green. The trailhead layer.',
    category: 'tops',
    image: 'https://pngimg.com/uploads/sweater/sweater_PNG33.png',
    colors: ['forest', 'olive'],
    seasons: ['autumn', 'winter'],
    brand: 'Patagonia',
    material: 'Recycled fleece',
    timesWorn: 24,
    lastWorn: daysAgo(5, 7, 30),
    createdAt: daysAgo(150),
    favorite: true,
  },
  {
    id: 'g-a14',
    name: 'Cashmere Turtleneck',
    description: 'Grade-A cashmere roll-neck in warm camel. Pure cold-weather luxury.',
    category: 'tops',
    image: 'https://pngimg.com/uploads/sweater/sweater_PNG34.png',
    colors: ['camel'],
    seasons: ['winter'],
    brand: 'Naadam',
    material: 'Cashmere',
    timesWorn: 10,
    lastWorn: daysAgo(30, 8, 0),
    createdAt: daysAgo(130),
    favorite: true,
  },
  {
    id: 'g-a15',
    name: 'Reverse-Weave Zip Hoodie',
    description: 'Heavyweight cotton-fleece zip hoodie in slate. Weekend-long comfort.',
    category: 'tops',
    image: 'https://pngimg.com/uploads/sweater/sweater_PNG35.png',
    colors: ['slate', 'charcoal'],
    seasons: ['spring', 'autumn'],
    brand: 'Champion',
    material: 'Cotton fleece',
    timesWorn: 38,
    lastWorn: daysAgo(3, 16, 0),
    createdAt: daysAgo(175),
    favorite: false,
  },
  {
    id: 'g-a16',
    name: 'Waffle-Knit Sweater',
    description: 'Chunky waffle-knit pullover in warm mustard. Adds a jolt to grey days.',
    category: 'tops',
    image: 'https://pngimg.com/uploads/sweater/sweater_PNG36.png',
    colors: ['mustard'],
    seasons: ['autumn'],
    brand: 'Todd Snyder',
    material: 'Cotton',
    timesWorn: 12,
    lastWorn: daysAgo(18, 9, 30),
    createdAt: daysAgo(100),
    favorite: false,
  },
  {
    id: 'g-a17',
    name: 'Striped Cotton Cardigan',
    description: 'Fine-gauge button cardigan with a nautical stripe. Brand-new to the rotation.',
    category: 'tops',
    image: 'https://pngimg.com/uploads/sweater/sweater_PNG37.png',
    colors: ['navy', 'cream'],
    seasons: ['spring', 'autumn'],
    brand: 'Sézane',
    material: 'Cotton',
    timesWorn: 0,
    lastWorn: null,
    createdAt: daysAgo(25),
    favorite: false,
  },
]
