import type { Garment } from '@/types/domain'
import { daysAgo } from '../mockData.dates'

/** Part B of the demo dataset: 10 bottoms + 7 dresses. */
export const GARMENTS_B: Garment[] = [
  // ── Bottoms (10) ──────────────────────────────────────────────
  {
    id: 'g-b01',
    image: 'https://pngimg.com/uploads/jeans/jeans_PNG5746.png',
    name: 'Dark Wash Slim Jeans',
    description: 'Deep indigo slim-fit jeans with a touch of stretch. Weekday default.',
    category: 'bottoms',
    colors: ['navy', 'denim'],
    seasons: ['autumn', 'winter', 'spring'],
    brand: 'Levi’s',
    material: 'Cotton denim',
    timesWorn: 38,
    lastWorn: daysAgo(3, 8, 30),
    createdAt: daysAgo(215),
    favorite: true,
  },
  {
    id: 'g-b02',
    image: 'https://pngimg.com/uploads/jeans/jeans_PNG5748.png',
    name: 'High-Rise Straight Jeans',
    description: 'Clean mid-blue straight leg with a flattering high rise.',
    category: 'bottoms',
    colors: ['denim', 'sky'],
    seasons: ['spring', 'summer', 'autumn'],
    brand: 'Everlane',
    material: 'Cotton denim',
    timesWorn: 22,
    lastWorn: daysAgo(6, 9, 15),
    createdAt: daysAgo(180),
    favorite: false,
  },
  {
    id: 'g-b03',
    image: 'https://pngimg.com/uploads/jeans/jeans_PNG5751.png',
    name: 'Cropped Mom Jeans',
    description: 'Rigid stone-wash mom jeans, cropped at the ankle. Retro ease.',
    category: 'bottoms',
    colors: ['denim', 'stone'],
    seasons: ['spring', 'summer'],
    brand: 'Weekday',
    material: 'Rigid denim',
    timesWorn: 15,
    lastWorn: daysAgo(12, 11, 0),
    createdAt: daysAgo(120),
    favorite: false,
  },
  {
    id: 'g-b04',
    image: 'https://pngimg.com/uploads/jeans/jeans_PNG5758.png',
    name: 'Black Skinny Jeans',
    description: 'Inky stretch skinnies that go with absolutely everything.',
    category: 'bottoms',
    colors: ['black', 'charcoal'],
    seasons: ['autumn', 'winter'],
    brand: 'Topshop',
    material: 'Stretch denim',
    timesWorn: 44,
    lastWorn: daysAgo(2, 8, 45),
    createdAt: daysAgo(240),
    favorite: true,
  },
  {
    id: 'g-b05',
    image: 'https://pngimg.com/uploads/jeans/jeans_PNG5765.png',
    name: 'Relaxed Boyfriend Jeans',
    description: 'Slouchy faded boyfriend jeans with a broken-in feel.',
    category: 'bottoms',
    colors: ['denim', 'slate'],
    seasons: ['spring', 'autumn'],
    brand: 'Agolde',
    material: 'Cotton denim',
    timesWorn: 12,
    lastWorn: daysAgo(19, 10, 30),
    createdAt: daysAgo(100),
    favorite: false,
  },
  {
    id: 'g-b06',
    image: 'https://pngimg.com/uploads/leggings/leggings_PNG22.png',
    name: 'Seamless Sculpt Leggings',
    description: 'Buttery seamless leggings with a high compressive waistband.',
    category: 'bottoms',
    colors: ['black'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    brand: 'Lululemon',
    material: 'Nylon blend',
    timesWorn: 51,
    lastWorn: daysAgo(1, 7, 0),
    createdAt: daysAgo(160),
    favorite: true,
  },
  {
    id: 'g-b07',
    image: 'https://pngimg.com/uploads/leggings/leggings_PNG28.png',
    name: 'High-Waist Yoga Leggings',
    description: 'Four-way-stretch leggings in heathered slate. Studio to street.',
    category: 'bottoms',
    colors: ['slate', 'charcoal'],
    seasons: ['spring', 'autumn', 'winter'],
    brand: 'Sweaty Betty',
    material: 'Recycled nylon',
    timesWorn: 29,
    lastWorn: daysAgo(4, 7, 30),
    createdAt: daysAgo(140),
    favorite: false,
  },
  {
    id: 'g-b08',
    image: 'https://pngimg.com/uploads/leggings/leggings_PNG34.png',
    name: 'Ribbed Ankle Leggings',
    description: 'Cosy ribbed leggings in muted olive. Lounge-and-errands staple.',
    category: 'bottoms',
    colors: ['olive', 'sage'],
    seasons: ['autumn', 'winter'],
    brand: 'Girlfriend Collective',
    material: 'Recycled polyester',
    timesWorn: 7,
    lastWorn: daysAgo(31, 18, 0),
    createdAt: daysAgo(70),
    favorite: false,
  },
  {
    id: 'g-b09',
    image: 'https://pngimg.com/uploads/leggings/leggings_PNG41.png',
    name: 'Cargo Utility Leggings',
    description: 'Slim khaki leggings with patch pockets. Casual utilitarian edge.',
    category: 'bottoms',
    colors: ['khaki'],
    seasons: ['spring', 'autumn'],
    material: 'Cotton blend',
    timesWorn: 3,
    lastWorn: null,
    createdAt: daysAgo(28),
    favorite: false,
  },
  {
    id: 'g-b10',
    image: 'https://pngimg.com/uploads/leggings/leggings_PNG47.png',
    name: 'Ponte Wide-Leg Trousers',
    description: 'Fluid ponte-knit wide legs in warm terracotta. Pull-on polish.',
    category: 'bottoms',
    colors: ['terracotta', 'rust'],
    seasons: ['autumn', 'winter', 'spring'],
    brand: 'Spanx',
    material: 'Ponte knit',
    timesWorn: 18,
    lastWorn: daysAgo(9, 9, 45),
    createdAt: daysAgo(110),
    favorite: true,
  },

  // ── Dresses (7) ───────────────────────────────────────────────
  {
    id: 'g-b11',
    image: 'https://pngimg.com/uploads/dress/dress_PNG120.png',
    name: 'Floral Midi Dress',
    description: 'Soft ditsy-print midi in blush. The easy warm-weather win.',
    category: 'dresses',
    colors: ['blush', 'cream'],
    seasons: ['spring', 'summer'],
    brand: '& Other Stories',
    material: 'Viscose',
    timesWorn: 9,
    lastWorn: daysAgo(10, 13, 0),
    createdAt: daysAgo(90),
    favorite: false,
  },
  {
    id: 'g-b12',
    image: 'https://pngimg.com/uploads/dress/dress_PNG125.png',
    name: 'Satin Slip Dress',
    description: 'Bias-cut satin slip in deep plum. Dinner-ready in seconds.',
    category: 'dresses',
    colors: ['plum', 'burgundy'],
    seasons: ['summer', 'autumn'],
    brand: 'Reformation',
    material: 'Satin',
    timesWorn: 14,
    lastWorn: daysAgo(16, 20, 30),
    createdAt: daysAgo(130),
    favorite: true,
  },
  {
    id: 'g-b13',
    image: 'https://pngimg.com/uploads/dress/dress_PNG130.png',
    name: 'Knit Sweater Dress',
    description: 'Cosy fine-gauge sweater dress in camel. Tights-and-boots season.',
    category: 'dresses',
    colors: ['camel', 'sand'],
    seasons: ['autumn', 'winter'],
    brand: 'Arket',
    material: 'Merino wool',
    timesWorn: 6,
    lastWorn: daysAgo(26, 12, 0),
    createdAt: daysAgo(75),
    favorite: false,
  },
  {
    id: 'g-b14',
    image: 'https://pngimg.com/uploads/dress/dress_PNG135.png',
    name: 'Crepe Wrap Dress',
    description: 'Fluid wrap dress in deep teal. Flatters and never creases.',
    category: 'dresses',
    colors: ['teal', 'emerald'],
    seasons: ['spring', 'autumn'],
    brand: 'Sézane',
    material: 'Crepe',
    timesWorn: 20,
    lastWorn: daysAgo(5, 18, 30),
    createdAt: daysAgo(150),
    favorite: true,
  },
  {
    id: 'g-b15',
    image: 'https://pngimg.com/uploads/dress/dress_PNG140.png',
    name: 'Tiered Cotton Sundress',
    description: 'Breezy tiered sundress in sun-baked mustard. Peak-summer joy.',
    category: 'dresses',
    colors: ['mustard', 'terracotta'],
    seasons: ['summer'],
    brand: 'Faithfull the Brand',
    material: 'Cotton',
    timesWorn: 11,
    lastWorn: daysAgo(7, 14, 0),
    createdAt: daysAgo(85),
    favorite: false,
  },
  {
    id: 'g-b16',
    image: 'https://pngimg.com/uploads/dress/dress_PNG145.png',
    name: 'Little Black Dress',
    description: 'Clean ponte sheath in black. The forever answer to “what do I wear?”',
    category: 'dresses',
    colors: ['black'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    brand: 'COS',
    material: 'Ponte knit',
    timesWorn: 27,
    lastWorn: daysAgo(11, 19, 0),
    createdAt: daysAgo(200),
    favorite: true,
  },
  {
    id: 'g-b17',
    image: 'https://pngimg.com/uploads/dress/dress_PNG150.png',
    name: 'Pleated Chiffon Maxi',
    description: 'Airy pleated maxi in pale sky. Floats through summer weddings.',
    category: 'dresses',
    colors: ['sky', 'lilac'],
    seasons: ['spring', 'summer'],
    brand: 'Zara',
    material: 'Chiffon',
    timesWorn: 4,
    lastWorn: null,
    createdAt: daysAgo(45),
    favorite: false,
  },
]
